### PR TITLE
Patterns/Progress tracker-spacing,design,text #988

### PR DESCRIPTION
**Pull request by jon-grant-state-ca-gov**
- Add media query for mobile timeline margin-bottom
- Update YY - YY text to Q1 - Q2, Q2 - Q3, etc
- Remove strong tags from step-list li headers

### CODE REVIEW

**Review by kkoryaka — CHANGES_REQUESTED** [review]
@jon-grant-state-ca-gov we cant have inline css styles because we cant expect users to copy those styles too. Could you find a solution without using those css? You can add those styles to core css since it's used by the component.

**Comment by jon-grant-state-ca-gov** [comment]
@kkoryaka I added a SASS file for the timeline change. Is that more like what you were talking about?

**Comment by kkoryaka** [comment]
@jon-grant-state-ca-gov I would add it into existing scss file: /source/scss/cagov/progress-bar.scss
Also, to me that class looks like this utility class m-b-0 (but for mobile) So you might make it m-b-0-mobile m-b-0-sm

**Comment by jon-grant-state-ca-gov** [comment]
@kkoryaka Ok, I was able to use those classes like you mentioned, thanks again!

**Review by kkoryaka — APPROVED** [review]
@jon-grant-state-ca-gov i am trying to figure out where did you added this mobile class m-b-0-mobile. Maybe i am missing it for some reason. But if you forgot to add it please add it to globals.scss

**Comment by jon-grant-state-ca-gov** [comment]
@kkoryaka I was able to add the class to those paragraphs in timeline.html. Doing it that way also made it to where I didn't need to remove the line breaks.

**Pull request merged**
