### PR TITLE
Smaller file size for favicon.ico

### PR DESCRIPTION
**Pull request by carterm**
Greatly reduces the size of `favicon.ico`

### CODE REVIEW

**Review by kkoryaka — APPROVED** [review]
Much(!) smaller favicon

**Comment by sharon-rabang** [comment]
@carterm How do I review it from here?

**Comment by carterm** [comment]
> @carterm How do I review it from here?

It's deployed to the dev site.

**Comment by sharon-rabang** [comment]
@carterm Looks good to go, thanks!

**Pull request merged**
