### PR TITLE
Patterns / Link grid - text edits #987

### PR DESCRIPTION
**Pull request by jon-grant-state-ca-gov**
- Add periods to each list item in accessibility.html

### CODE REVIEW

**Review by kkoryaka — CHANGES_REQUESTED** [review]
Remove them. I talked to content team. They are working on the standards that they going to implement after production release. But for now we have agreed to remove them.
cc @extinah cc @ashleydraper

**Comment by ashleydraper** [comment]
Thanks for copying me on this. Standards on this topic are absolutely necessary because there are instances where it makes sense to include them (see screenshot). 

Also, I think we are missing a colon here-

image

**Comment by jon-grant-state-ca-gov** [comment]
@kkoryaka @ashleydraper Ok so just to clarify, remove the periods, but add the colon?

**Comment by jon-grant-state-ca-gov** [comment]
@kkoryaka 
- Removed periods from accessibility.html
- Added colon to color.html

**Review by kkoryaka — APPROVED** [review]
perfect

**Pull request merged**
